# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Running the push/merge on main
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: bankingGo2
          POSTGRES_USER: bankingGo2
          POSTGRES_DB: bankingGo2
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5433:5432"
          
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
          pg_isready -h localhost -p 5433 -U bankingGo2 && break
          echo "Waiting for PostgreSQL..."
          sleep 5
          done

      - name: Checkout code into go module directory...
        uses: actions/checkout@v2

      - name: Install migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Making migrations
        run: make migrateup

      - name: Build
        run: go build -v ./...

      - name: Test
        run: make test
