# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Running the push/merge on main
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: bankingGo2
          POSTGRES_USER: bankingGo2
          POSTGRES_DB: bankingGo2
          POSTGRES_PORT: 5433
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Checkout code into go module directory...
      uses: actions/checkout@v2

    - name: Making migrations
      run: make migrateup

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test
